[package]
name = "wright-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Application orchestration engine for Wright"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
figment = { version = "0.10.19", features = ["toml", "env"] }
futures-util = "0.3.32"
git2 = { version = "0.21", features = ["vendored-libgit2", "vendored-openssl"] }
globset = "0.4"
indicatif = "0.18"
libc = "0.2"
nix = { version = "0.29", features = ["sched", "mount", "signal", "process", "hostname", "user", "fs"] }
owo-colors = "4"
regex = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10"
similar = "2"
tempfile = "3"
thiserror = "2"
tokio = { version = "1.52.1", features = ["full"] }
toml = "0.8"
tracing = "0.1"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "time"] }
uuid = { version = "1", features = ["v4", "serde"] }
walkdir = "2"
wright-model = { path = "../wright-model" }
wright-part = { path = "../wright-part" }
wright-plan = { path = "../wright-plan" }
wright-state = { path = "../wright-state" }

[lints]
workspace = true
