[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "link-arg=-static-libgcc"]

[build]
rustflags = ["-C", "link-arg=-static-libgcc"]

[env]
LZMA_API_STATIC = "1"
LIBZ_SYS_STATIC = "1"
